### ISSUE TITLE
Missing type definitions

### ISSUE THREAD

**Issue by felhag** [tofiqquadri/ngx-csv-parser#23]
Hey, thanks for updating to Angular 13! I think something went wrong when building the 1.0.8 release since all type definitions are missing. This makes it impossible to import code from the ngx-csv-parser. Imports show the following error while :

`TS2307: Cannot find module 'ngx-csv-parser' or its corresponding type declarations.`

**Comment by tofiqquadri** [comment]
@felhag can you share the complete log?

**Comment by tofiqquadri** [comment]
@felhag check the implementation now. Version 1.1.0 should fix that problem.

**Comment by tofiqquadri** [comment]
@felhag check and close the issue if it is solved

**Comment by hmG3** [comment]
@tofiqquadri Installed 1.1.0 version. The error is still here. Cannot import anything from the library

**Comment by felhag** [comment]
Same, it's still missing the type defs (the .d.ts files):

![image](https://user-images.githubusercontent.com/62592273/159176455-a957f965-adec-4f46-b274-1137f2167c5b.png)

**Comment by tofiqquadri** [comment]
@felhag are you using the latest version? 1.1.0

Can you share the sample of your project to reproduce the issue?

**Comment by felhag** [comment]
I created a stackblitz to illustrate the problem: https://stackblitz.com/edit/angular-ivy-vfwssb. If you change the ngx-csv-parser version to 0.0.7 and reload the dependencies it compiles fine.

**Comment by tofiqquadri** [comment]
@felhag try ngx-csv-parser version 1.1.1 now.

**Comment by tofiqquadri** [comment]
@felhag I upgraded to 1.1.1 and the issue is solved:

![image](https://user-images.githubusercontent.com/16437112/159229033-fabe27fb-d8fb-4d60-8505-436e53fde869.png)

**Comment by felhag** [comment]
Jep, looks good, thanks for the quick response. I'll close the issue.

**Comment by tofiqquadri** [comment]
> Jep, looks good, thanks for the quick response. I'll close the issue.

No problem. Actually, the issue is due to a major upgrade in the Angular version & Ivy causes this issue preventing types of files from being published. Had to learn this hard way.
